jobs:
  include:
    - name: VM
      os: linux-ppc64le
      dist: focal
    - name: container
      arch: ppc64le
      dist: focal

addons:
  snaps:
    - name: snapcraft
      channel: stable
      confinement: classic
    - name: lxd
      channel: stable

script:
  - sudo apt-get update -y 
  - sudo apt install snapd
  - sudo snap refresh lxd --channel=5.8/stable
  - sudo usermod --append --groups lxd $USER
#   - sudo /snap/bin/lxd.migrate -yes
  - sudo /snap/bin/lxd waitready
  - sudo /snap/bin/lxd init --auto

#   - export SNAPCRAFT_BUILD_ENVIRONMENT=lxd
  
  - cd ~
  - git clone https://github.com/anup-kodlekere/worker.git
  - cd worker
  - git checkout deploy_snap
  - snapcraft build --use-lxd
