language: go

go: 1.18.x

arch: ppc64le
os: linux
dist: focal
#os: linux-ppc64le

# env:
#   global:
#   - AMQP_URI="amqp://"
#   - GOPATH="$HOME/gopath"
#   - PATH="bin:$HOME/gopath/bin:$HOME/bin:$PATH"
#   - CHECKOUT_ROOT="$HOME/gopath/src/github.com/travis-ci/worker"
#   - GO15VENDOREXPERIMENT='1'
#   - REDIS_URL="redis://"

# stages:
# - test

# before_cache:
# - make clean

before_script:
  - sudo apt-get update -y 
  - sudo apt-get install snapd
  - snap list
  - sudo snap install lxd --stable
  - sudo snap install snapcraft --classic
  - lxc version

script:
  - |
    export SNAPCRAFT_BUILD_ENVIRONMENT=lxd
    snapcraft
    ls
    
