jobs:
  include:
    - name: VM
      os: linux-ppc64le
      dist: focal
    - name: container
      arch: ppc64le
      dist: focal

addons:
  snaps:
    - name: snapcraft
      channel: stable
      confinement: classic
    - name: lxd
      channel: stable

script:
  - sudo apt-get update -y 
#   - sudo apt-get purge 
  - sudo apt install snapd
  - sudo snap refresh lxd --channel=5.8/stable
  - sudo usermod --append --groups lxd $USER
#   - sudo /snap/bin/lxd.migrate -yes
  - sudo lxd waitready
  - sudo lxd init --auto
  - sudo lxd init --dump
  - lxc profile set default security.privileged true
  - which lxc
  - which lxd
  - export SNAPCRAFT_BUILD_ENVIRONMENT=lxd
  - export SNAPCRAFT_BUILD_INFO=1
  - cd ~
  - git clone https://github.com/anup-kodlekere/worker.git
  - cd worker
  - git checkout deploy_snap
  - sudo snapcraft build --use-lxd
