language: go

go: 1.18.x

arch: ppc64le
os: linux
dist: focal


addons:
  snaps:
    - name: snapcraft
      channel: stable
      confinement: classic
    - name: lxd
      channel: stable

before_script:
  - sudo apt-get update -y 
  - sudo snap refresh lxd --channel=5.8/stable
  - snap list
  - lxc version

script:
  - export SNAPCRAFT_BUILD_ENVIRONMENT=lxd
  - snapcraft
  - ls
