language: go

go: 1.18.x

arch: ppc64le
os: linux
dist: focal

addons:
  snaps:
    - name: snapcraft
      channel: stable
      confinement: classic
    - name: lxd
      channel: stable

script:
  - sudo apt-get update -y 
  - sudo snap refresh lxd --channel=5.8/stable
  - snap list
  - sudo lxd init --auto
#  - sudo lxd init --preseed < lxd_preseed.yml
  - export SNAPCRAFT_BUILD_ENVIRONMENT=lxd
  
  - cd ~
  - git clone https://github.com/anup-kodlekere/worker.git
  - cd worker
  - pwd
  - ls -lha
  - which snapcraft
  - snapcraft build
  - snapcraft
