jobs:
  include:
    - name: VM
      os: linux-ppc64le
      dist: bionic
      before_script:
        - sudo rm -f /etc/apt/sources.list.d/pgdg.list
        - sudo rm -f /etc/apt/sources.list.d/pgdg.list.save
      script:
        - sudo apt-get update -y
        - sudo apt-get install snapd -y
        - sudo snap install lxd --channel=5.8/stable
        - sudo snap install snapcraft --classic
        - sudo /snap/bin/lxd init --auto
        - snap list
        - sudo /snap/bin/lxd.migrate -yes
        - sudo /snap/bin/lxd waitready
        - sudo /snap/bin/lxd init --dump
        - sudo lxc profile set default security.privileged true

        - export SNAPCRAFT_BUILD_ENVIRONMENT=lxd
        - export SNAPCRAFT_BUILD_INFO=1

        - cd ~
        - git clone https://github.com/anup-kodlekere/worker.git
        - cd worker
        - git checkout deploy_snap
        - sudo snapcraft --use-lxd
        - sg lxd -c snapcraft
        
        
    - name: container
      arch: ppc64le
      dist: focal
      addons:
        snaps:
          - name: snapcraft
            channel: stable
            confinement: classic
          - name: lxd
            channel: stable


      script:
        - sudo apt-get update -y 
        - sudo apt install snapd
        - sudo snap refresh lxd --channel=5.8/stable
        - sudo usermod --append --groups lxd $USER

#         - sudo /snap/bin/lxd.migrate -yes
#         - sudo lxd waitready

        - sudo lxd init --auto
        - sudo lxd init --dump
        - sudo lxc profile set default security.privileged true

        - export SNAPCRAFT_BUILD_ENVIRONMENT=lxd
        - export SNAPCRAFT_BUILD_INFO=1

        - cd ~
        - git clone https://github.com/anup-kodlekere/worker.git
        - cd worker
        - git checkout deploy_snap
        - sg lxd -c snapcraft
      #   - sudo snapcraft build --use-lxd


# before_script:
#   - cat /etc/subuid > tsubuid
#   - sudo echo "root:1000000:65536" >> tsubuid
#   - sudo cp tsubuid /etc/subuid
#   - rm -f tsubuid
  
#   - cat /etc/subuid > tsubgid
#   - sudo echo "root:1000000:65536" >> tsubgid
#   - sudo cp tsubgid /etc/subgid
#   - rm -f tsubgid
  
#   - sudo cat /etc/subuid
#   - sudo cat /etc/subgid
